apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: suneel717/flask-app:latest  # Make sure you have pushed this image to Docker Hub
        ports:
        - containerPort: 5000
